### PR TITLE
Bold the email and the phone number in the footer

### LINKED ISSUE #72: Bold the footer email and phone number
**Is your feature request related to a problem? Please describe.**
Currently, can't see the email and the phone numbers as links

**Describe the solution you'd like**
Bold the footer email and phone number to show it as a link

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
## Purpose

The purpose of this Pull Request is to fix #72 

## Goals

Bold the email and the phone number in the footer

## Approach

Bold the email and the phone number in the footer

### Screenshots

image

  
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@SilunaP brother can you review this PR?

**Comment by SilunaP** [comment]
@YoshithaRathnayake can you change this to become bold when the cursor is hovered above those texts

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake can you change this to become bold when the cursor is hovered above those texts

Sure @SilunaP

**Comment by YoshithaRathnayake** [comment]
@SilunaP brother can you review this now?

**Comment by SilunaP** [comment]
Ok

**Pull request merged**
